listen: :10008

tls:
  cert: /home/container/h2/cert.pem
  key: /home/container/h2/key.pem

auth:
  type: password
  password: 'HY2_PASSWORD'

dns:
  - 1.1.1.1
  - 8.8.8.8
  - 9.9.9.9

quic:
  init_stream_window: 524288
  max_idle_timeout: 30s
